name = "rosso-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"

# 添加Node.js兼容性标志
compatibility_flags = ["nodejs_compat"]

# D1数据库配置
d1_databases = [
  { binding = "DB", database_name = "SSO_DB", database_id = "e14921f4-a19b-4ddb-8e4b-b251ed96f213" }
]

# Cloudflare KV命名空间配置
[[kv_namespaces]]
binding = "SSO_STORE"
id = "85833268e8dc472a97aa0a1dd26130b3"
preview_id = "SSO_STORE"

[[kv_namespaces]]
binding = "APPLICATIONS"
id = "db9d8c52cf124152974bdcb5166567c9"
preview_id = "APPLICATIONS"

# Routes配置 - 正确位置
routes = [
  { pattern = "/api/*", zone_name = "sso.prooo.me" }
]

# 环境变量配置，在实际部署时通过Cloudflare Dashboard或wrangler secret设置
[vars]
JWT_SECRET = "yHJRAvRJIKGIuhGLFhUtFAGxkNvxXa4Bfeom9bqFlqU=" # 使用wrangler secret put JWT_SECRET "your-secret"设置
COOKIE_SECRET = "YyL4wwNGAOtz19Qe4oouU8mn2dWmGig+eco5ASCWnRk=" # 使用wrangler secret put COOKIE_SECRET "your-secret"设置
SSO_DOMAIN = "sso.prooo.me" # 实际域名
ENVIRONMENT = "production"

# 开发环境配置
[env.development]
[env.development.vars]
ENVIRONMENT = "development"
JWT_SECRET = "dev-secret-key"
COOKIE_SECRET = "dev-cookie-secret"
SSO_DOMAIN = "localhost"

# 禁用遥测
send_metrics = false
