name = "cloudflare-sso-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"

# 添加Node.js兼容性标志
compatibility_flags = ["nodejs_compat"]


# D1数据库配置
d1_databases = [
  { binding = "DB", database_name = "SSO_DB", database_id = "your_database_id" }
]

# Cloudflare KV命名空间配置
[[kv_namespaces]]
binding = "SSO_STORE"
id = "your_kv_namespace_id"
preview_id = "your_kv_preview_namespace_id"



# Routes配置
routes = [
  { pattern = "/api/*", script = "cloudflare-sso-worker", zone_name = "sso.prooo.me" }
]

# 环境变量配置，在实际部署时通过Cloudflare Dashboard或wrangler secret设置
[vars]
JWT_SECRET = "" # 使用wrangler secret put JWT_SECRET "your-secret"设置
COOKIE_SECRET = "" # 使用wrangler secret put COOKIE_SECRET "your-secret"设置
SSO_DOMAIN = "sso.prooo.me" # 实际域名
ENVIRONMENT = "production"

# 开发环境配置
[env.development]
[env.development.vars]
ENVIRONMENT = "development"
JWT_SECRET = "dev-secret-key"
COOKIE_SECRET = "dev-cookie-secret"
SSO_DOMAIN = "localhost"

# 禁用遥测
send_metrics = false
